### ISSUE TITLE
Browser stop working

### ISSUE THREAD

**Issue by islam2hamy** [plateaukao/browser#20] opened 2021-06-04 14:36 UTC
Click on tab count icon from toolbar
Click the new tab icon
Click back to close the keyboard
Close the browser
Open the browser

Browser stop working

**Comment by plateaukao** [comment] 2021-06-04 16:36
Hi, @islam2hamy  could you share a video recording with the above steps?
I tried locally, it works on my Hisense device.

**Comment by islam2hamy** [comment] 2021-06-04 16:46
Here you are

<div style="width:100%;height:0px;position:relative;padding-bottom:177.778%;"><iframe src="https://streamable.com/e/130lyl?autoplay=1" frameborder="0" width="100%" height="100%" allowfullscreen allow="autoplay" style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>

**Comment by plateaukao** [comment] 2021-06-05 04:09
@islam2hamy  did you turn on "save tabs" feature in Settings? I think it might be an issue caused by that feature. I will try to find what went wrong. Thanks for reporting the issue.

**Comment by plateaukao** [comment] 2021-06-05 04:25
I found the root cause. Will fix it in next version.

**Comment by islam2hamy** [comment] 2021-06-05 05:06
> @islam2hamy did you turn on "save tabs" feature in Settings? I think it might be an issue caused by that feature. I will try to find what went wrong. Thanks for reporting the issue.

Yes

**Comment by islam2hamy** [comment] 2021-06-05 05:06
> I found the root cause. Will fix it in next version.

Nice work

**Comment by plateaukao** [comment] 2021-06-05 10:16
Fixed in https://github.com/plateaukao/browser/releases/tag/v8.8.1

**Closed by plateaukao** 2021-06-05 10:16 UTC
