### ISSUE TITLE
Clicking on the link will bring up the input method

### ISSUE THREAD

**Issue by gifcode** [plateaukao/browser#16] opened 2021-05-23 14:32 UTC
Clicking on the link will bring up the input method

![1](https://user-images.githubusercontent.com/84230167/119264468-f246e680-bc15-11eb-9981-95ed158b1480.gif)

**Comment by plateaukao** [comment] 2021-05-26 16:51
Hi, @gifcode 
May I know 
1. which version of EinkBro are you using?
2. what device are you using? What version of Android OS is it?

I tried the same behavior on Baidu.com desktop mode on my Hisense A7. It seems everything works fine.

**Comment by gifcode** [comment] 2021-05-27 11:05
EinkBro  8.7.5
device    墨案 moaan inkpad x
Android   8.1

**Comment by gifcode** [comment] 2021-05-27 11:06
> 嗨，@gifcode
> 我可以知道吗
> 
> 1. 您使用的是哪个版本的艾克布罗？
> 2. 您使用的是什么设备？它是什么版本的安卓操作系统？
> 
> 我在海信 A7 上的桌面模式上尝试了相同的行为 Baidu.com。看来一切正常。

EinkBro 8.7.5
device 墨案 moaan inkpad x
Android 8.1

**Comment by gifcode** [comment] 2021-05-27 11:07
> Hi, @gifcode
> May I know
> 
> 1. which version of EinkBro are you using?
> 2. what device are you using? What version of Android OS is it?
> 
> I tried the same behavior on Baidu.com desktop mode on my Hisense A7. It seems everything works fine.

EinkBro 8.7.5
device 墨案 moaan inkpad x
Android 8.1

**Comment by plateaukao** [comment] 2021-05-29 06:36
Hi, @gifcode 

Does this happen to other websites too? (clicking on link, it will always bring up the input method), or it only happens on Baidu.com?

If it only happens on Baidu.com, it may be because Baidu.com did something to trigger that on Moaan inkpad, which I didn't find in other Eink devices.

Sorry that I don't have Moaan inkpad devices, so I can't look further into this issue.

**Comment by gifcode** [comment] 2021-05-29 13:11
> Hi, @gifcode
> 
> Does this happen to other websites too? (clicking on link, it will always bring up the input method), or it only happens on Baidu.com?
> 
> If it only happens on Baidu.com, it may be because Baidu.com did something to trigger that on Moaan inkpad, which I didn't find in other Eink devices.
> 
> Sorry that I don't have Moaan inkpad devices, so I can't look further into this issue.
yes ， on desktop mode ,other websites link will bring up the input method  .but Some websites built for Mobile phones work fine.
I tried some Android emulators,Found an Android emulators have a the same problem

![捕获](https://user-images.githubusercontent.com/84230167/120071499-4fcdae00-c0c2-11eb-9839-e19f9790aa86.PNG)
https://www.yeshen.com/


https://user-images.githubusercontent.com/84230167/120071483-3f1d3800-c0c2-11eb-8f6a-2f9fae114d62.mp4

**Comment by plateaukao** [comment] 2021-05-29 17:46
Hi, @gifcode 
thanks for providing the link of simulator. I tried to install it, but found it needs some system permissions in order to install successfully, so I didn't try it in the end. However, I found I can reproduce it with normal emulator with Android OS 8.1

The issue should be fixed in version 8.7.6. Please try to use that version: https://github.com/plateaukao/browser/releases/tag/v8.7.6

**Closed** 2021-05-30 07:07 UTC
